In [1]:
# Imports all necessary libraries
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

In [2]:
# Loads dataset #1
data = pd.read_csv("../data/GenZ_DatingApp_Data.csv")

In [3]:
data2 = pd.read_csv("../data/DatingData2.csv")

In [4]:
# Display the first dataset

data

,User_ID,Age,Gender,Location,Education,Occupation,Primary_App,Secondary_Apps,Usage_Frequency,Daily_Usage_Time,Reason_for_Using,Satisfaction,Challenges,Desired_Features,Preferred_Communication,Partner_Priorities
0,1,20,Non-binary,Bangalore,Undergraduate,Freelancer,Hinge,Hinge,Monthly,1 hour,Finding a Partner,4,Safety Concerns,Audio Calls,Video Calls,Values > Personality > Appearance
1,2,24,Female,Delhi,Undergraduate,Part-time Job,Hinge,OkCupid,Weekly,30 minutes,Casual Dating,5,Time-Wasting,Video Calls,Text,Values > Personality > Appearance
2,3,24,Non-binary,Kolkata,Undergraduate,Intern,NaN,NaN,Weekly,2 hours,Casual Dating,4,Safety Concerns,Detailed Profiles,Text,Values > Personality > Appearance
3,4,22,Non-binary,Delhi,Graduate,Full-time Job,NaN,OkCupid,Daily,30 minutes,Casual Fun,3,NaN,AI Recommendations,Voice Notes,Personality > Interests > Values
4,5,18,Male,Delhi,Graduate,Intern,OkCupid,OkCupid,Weekly,2 hours,Casual Fun,4,Safety Concerns,Video Calls,Text,Appearance > Interests > Personality
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,496,23,Female,Mumbai,Undergraduate,Intern,Tinder,Hinge,Weekly,1.5 hours,Casual Dating,2,NaN,Audio Calls,Voice Notes,Personality > Interests > Values
496,497,23,Male,Mumbai,Postgraduate,Intern,OkCupid,Tinder,Daily,2 hours,Casual Fun,1,Time-Wasting,Video Calls,Video Calls,Values > Personality > Appearance
497,498,22,Male,Hyderabad,Graduate,Freelancer,NaN,Hinge,Monthly,2 hours,Casual Fun,2,Lack of Genuine Matches,Video Calls,Voice Notes,Appearance > Interests > Personality
498,499,21,Female,Kolkata,Graduate,Student,Tinder,Hinge,Daily,1.5 hours,Casual Dating,3,Lack of Genuine Matches,Detailed Profiles,Text,Appearance > Interests > Personality
499,500,22,Male,Mumbai,Graduate,Part-time Job,NaN,Hinge,Weekly,1.5 hours,Casual Fun,2,Time-Wasting,AI Recommendations,Video Calls,Appearance > Interests > Personality

In [5]:
# Display the second dataset

data2

,User_ID,Hobbies,Favorite_Music,Ideal_First_Date,Relationship_Type
0,1,"Reading, Traveling",Indie,Coffee Shop,Long-term
1,2,"Movies, Sports",Pop,Movie Night,Casual
2,3,"Cooking, Gaming",Rock,Dinner at Home,Long-term
3,4,"Hiking, Music",Jazz,Picnic,Casual
4,5,"Art, Photography",Classical,Art Gallery,Long-term
...,...,...,...,...,...
495,496,"Reading, Traveling",Jazz,Bookstore Visit,Long-term
496,497,"Dancing, Crafting",Classical,Craft Night,Casual
497,498,"Photography, Cooking",Hip-Hop,Culinary Class,Long-term
498,499,"Cooking, Hiking",R&B,Picnic in the Park,Casual
499,500,"Traveling, Fitness",EDM,Outdoor Adventure,Long-term

In [6]:
# Merge tha data

merged_data = pd.merge(data, data2, on = 'User_ID', how = 'outer')

##### Why I Chose an Outer Join
- An outer join ensures that all rows from both datasets are included in the final combined dataset, even if there are no matching rows in the other dataset.
- If there are rows in one dataset that do not have corresponding matches in the other, the outer join will still include them, filling in NaN (Not a Number) for missing values.
- This approach allows us to analyze the entire dataset, including records that may not have matches, which is useful for identifying gaps or inconsistencies.

##### Type of NA Values Created
- If a row exists in clean_data but not in new_data (or vice versa), the columns from the missing dataset will be filled with NaN.
- If the datasets have columns with the same name (other than the join key), pandas will automatically append suffixes (_x for the left dataset and _y for the right dataset) to distinguish them. These columns may also contain NaN values if there are no matches.

In [8]:
# Display the merged dataset

merged_data

,User_ID,Age,Gender,Location,Education,Occupation,Primary_App,Secondary_Apps,Usage_Frequency,Daily_Usage_Time,Reason_for_Using,Satisfaction,Challenges,Desired_Features,Preferred_Communication,Partner_Priorities,Hobbies,Favorite_Music,Ideal_First_Date,Relationship_Type
0,1,20,Non-binary,Bangalore,Undergraduate,Freelancer,Hinge,Hinge,Monthly,1 hour,Finding a Partner,4,Safety Concerns,Audio Calls,Video Calls,Values > Personality > Appearance,"Reading, Traveling",Indie,Coffee Shop,Long-term
1,2,24,Female,Delhi,Undergraduate,Part-time Job,Hinge,OkCupid,Weekly,30 minutes,Casual Dating,5,Time-Wasting,Video Calls,Text,Values > Personality > Appearance,"Movies, Sports",Pop,Movie Night,Casual
2,3,24,Non-binary,Kolkata,Undergraduate,Intern,NaN,NaN,Weekly,2 hours,Casual Dating,4,Safety Concerns,Detailed Profiles,Text,Values > Personality > Appearance,"Cooking, Gaming",Rock,Dinner at Home,Long-term
3,4,22,Non-binary,Delhi,Graduate,Full-time Job,NaN,OkCupid,Daily,30 minutes,Casual Fun,3,NaN,AI Recommendations,Voice Notes,Personality > Interests > Values,"Hiking, Music",Jazz,Picnic,Casual
4,5,18,Male,Delhi,Graduate,Intern,OkCupid,OkCupid,Weekly,2 hours,Casual Fun,4,Safety Concerns,Video Calls,Text,Appearance > Interests > Personality,"Art, Photography",Classical,Art Gallery,Long-term
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,496,23,Female,Mumbai,Undergraduate,Intern,Tinder,Hinge,Weekly,1.5 hours,Casual Dating,2,NaN,Audio Calls,Voice Notes,Personality > Interests > Values,"Reading, Traveling",Jazz,Bookstore Visit,Long-term
496,497,23,Male,Mumbai,Postgraduate,Intern,OkCupid,Tinder,Daily,2 hours,Casual Fun,1,Time-Wasting,Video Calls,Video Calls,Values > Personality > Appearance,"Dancing, Crafting",Classical,Craft Night,Casual
497,498,22,Male,Hyderabad,Graduate,Freelancer,NaN,Hinge,Monthly,2 hours,Casual Fun,2,Lack of Genuine Matches,Video Calls,Voice Notes,Appearance > Interests > Personality,"Photography, Cooking",Hip-Hop,Culinary Class,Long-term
498,499,21,Female,Kolkata,Graduate,Student,Tinder,Hinge,Daily,1.5 hours,Casual Dating,3,Lack of Genuine Matches,Detailed Profiles,Text,Appearance > Interests > Personality,"Cooking, Hiking",R&B,Picnic in the Park,Casual
499,500,22,Male,Mumbai,Graduate,Part-time Job,NaN,Hinge,Weekly,1.5 hours,Casual Fun,2,Time-Wasting,AI Recommendations,Video Calls,Appearance > Interests > Personality,"Traveling, Fitness",EDM,Outdoor Adventure,Long-term

In [9]:
# Check for NA values

merged_data.isna().sum()

User_ID                      0
Age                          0
Gender                       0
Location                     0
Education                    0
Occupation                   0
Primary_App                107
Secondary_Apps             114
Usage_Frequency              0
Daily_Usage_Time             0
Reason_for_Using             0
Satisfaction                 0
Challenges                 117
Desired_Features             0
Preferred_Communication      0
Partner_Priorities           0
Hobbies                      0
Favorite_Music               0
Ideal_First_Date             0
Relationship_Type            0
dtype: int64

In [10]:
# Drops rows where all columns are NA values

clean_merge = merged_data.dropna(how = "all")

In [11]:
# Display the clean data

clean_merge

,User_ID,Age,Gender,Location,Education,Occupation,Primary_App,Secondary_Apps,Usage_Frequency,Daily_Usage_Time,Reason_for_Using,Satisfaction,Challenges,Desired_Features,Preferred_Communication,Partner_Priorities,Hobbies,Favorite_Music,Ideal_First_Date,Relationship_Type
0,1,20,Non-binary,Bangalore,Undergraduate,Freelancer,Hinge,Hinge,Monthly,1 hour,Finding a Partner,4,Safety Concerns,Audio Calls,Video Calls,Values > Personality > Appearance,"Reading, Traveling",Indie,Coffee Shop,Long-term
1,2,24,Female,Delhi,Undergraduate,Part-time Job,Hinge,OkCupid,Weekly,30 minutes,Casual Dating,5,Time-Wasting,Video Calls,Text,Values > Personality > Appearance,"Movies, Sports",Pop,Movie Night,Casual
2,3,24,Non-binary,Kolkata,Undergraduate,Intern,NaN,NaN,Weekly,2 hours,Casual Dating,4,Safety Concerns,Detailed Profiles,Text,Values > Personality > Appearance,"Cooking, Gaming",Rock,Dinner at Home,Long-term
3,4,22,Non-binary,Delhi,Graduate,Full-time Job,NaN,OkCupid,Daily,30 minutes,Casual Fun,3,NaN,AI Recommendations,Voice Notes,Personality > Interests > Values,"Hiking, Music",Jazz,Picnic,Casual
4,5,18,Male,Delhi,Graduate,Intern,OkCupid,OkCupid,Weekly,2 hours,Casual Fun,4,Safety Concerns,Video Calls,Text,Appearance > Interests > Personality,"Art, Photography",Classical,Art Gallery,Long-term
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,496,23,Female,Mumbai,Undergraduate,Intern,Tinder,Hinge,Weekly,1.5 hours,Casual Dating,2,NaN,Audio Calls,Voice Notes,Personality > Interests > Values,"Reading, Traveling",Jazz,Bookstore Visit,Long-term
496,497,23,Male,Mumbai,Postgraduate,Intern,OkCupid,Tinder,Daily,2 hours,Casual Fun,1,Time-Wasting,Video Calls,Video Calls,Values > Personality > Appearance,"Dancing, Crafting",Classical,Craft Night,Casual
497,498,22,Male,Hyderabad,Graduate,Freelancer,NaN,Hinge,Monthly,2 hours,Casual Fun,2,Lack of Genuine Matches,Video Calls,Voice Notes,Appearance > Interests > Personality,"Photography, Cooking",Hip-Hop,Culinary Class,Long-term
498,499,21,Female,Kolkata,Graduate,Student,Tinder,Hinge,Daily,1.5 hours,Casual Dating,3,Lack of Genuine Matches,Detailed Profiles,Text,Appearance > Interests > Personality,"Cooking, Hiking",R&B,Picnic in the Park,Casual
499,500,22,Male,Mumbai,Graduate,Part-time Job,NaN,Hinge,Weekly,1.5 hours,Casual Fun,2,Time-Wasting,AI Recommendations,Video Calls,Appearance > Interests > Personality,"Traveling, Fitness",EDM,Outdoor Adventure,Long-term

In [12]:
# save the script

# Generate the file name with today's date
file_name = "MergedData_" + ".csv"

# Save the DataFrame to a CSV file
clean_merge.to_csv(file_name, index=False)

# Print confirmation
print(f"Data saved as {file_name}")

Data saved as MergedData_.csv